### ISSUE TITLE
All the links in readme are broken - guide, concepts, ...

### ISSUE THREAD

**Issue by devlibx** [raystack/dagger#225]
**Description**
The readme links are broken and not landing to a 404 page

**To Reproduce**
1. Go to README page
2. Select a line e.g. Guide under usage section

Expected vs actual behavior
Most of the links do not work

**Expected behavior**
I expected that I will land to some page where I can get more info

**Additional context**
na

**Comment by ravisuhag** [comment]
@devlibx This is fixed now.
